### ISSUE TITLE
Open to using bakeware on this project?

### ISSUE THREAD

**Issue by michaelvigor** [wojtekmach/mini_repo#37]
Hello,

I was reading about the new tool [Bakeware](https://github.com/spawnfest/bakeware) (Compile Elixir applications into single, easily distributed executable binaries) - and it struck me that a project like mini_repo may be a good fit for using it. You could start your own local repo after downloading and running a single file. 

I thought probably best to raise this idea in an issue before starting on the PR, just to guage whether this is good/bad idea 😄

**Comment by ericmj** [comment]
Hi,

Bakeware seems like a great tool but there are many ways to package applications and it's hard to support them all. Bakeware mostly seems useful if you want to provide pre-compiled binaries, but I don't think there are any plans for that, specially since it doesn't seem straightforward to cross-compile.

If you want to use Bakeware it seems to be just a few steps to add it to your own copy of mini_repo so I would suggest doing that instead of adding it to this repository.

**Comment by michaelvigor** [comment]
OK, no problem. Thanks for taking the time to give this feedback!
