### ISSUE TITLE
Is it currently possible to publish and read a package?

### ISSUE THREAD

**Issue by isaacsanders** [wojtekmach/mini_repo#6]
@asummers and I can't see any of the package fetching GET requests implemented.

Is fetching a package implemented?

**Comment by wojtekmach** [comment]
Yes, we don't implement these endpoints per se, instead we rely on Plug.Static to serve the files from a known location: https://github.com/wojtekmach/mini_repo/blob/master/lib/mini_repo/endpoint.ex#L8:L10

the idea was this should be enough for serving local files, and if you e.g. store files on S3, then it likely makes sense to have your _repo url_, which is always read-only, point directly to S3 (or something else in front of s3) rather than to your MiniRepo instance. (Publishing is done through an _api url_). In other cases you'd need to implement the repo endpoints yourself, here's the spec: https://github.com/hexpm/specifications/blob/master/endpoints.md#endpoints-1

does that make sense?

**Comment by isaacsanders** [comment]
It makes sense, but it isn't great from a perspective of building authentication/etc into the mini_repo.

**Comment by isaacsanders** [comment]
If this is just meant to be a POC, then it probably isn't a big deal.

**Comment by wojtekmach** [comment]
> It makes sense, but it isn't great from a perspective of building authentication/etc into the mini_repo.

why not? all you need to do is implement an auth plug and put it before Plug.Static.

> If this is just meant to be a POC, then it probably isn't a big deal.

As we mentioned in [Contributing](https://github.com/wojtekmach/mini_repo#contributing) section of the readme, the goal is to have a minimal server that is already usable (even if in limited way), and be easy to adjust for your orgs specific needs.

I'm gonna close this issue as it's not actionable, but feel free to keep the discussion going.

**Comment by isaacsanders** [comment]
Thanks for chatting about this, wojtek.
